In [7]:
ALPACA_API_KEY = "PKVQE7BUOAC40D5OSCHH"
ALPACA_SECRET_KEY = "DfXHYuZpMlmON3mcHPVTQDWZTnnMyt95PyaDtlAF"


In [8]:
import pandas as pd
import numpy as np



In [9]:
import alpaca_trade_api as tradeapi
import os

In [10]:
alpaca_api_key = os.getenv("ALPACA_API_KEY")
alpaca_secret_key = os.getenv("ALPACA_SECRET_KEY")

In [29]:
alpaca_api_key


In [11]:
## Set Alpaca API key and secret
alpaca_api_key = ALPACA_API_KEY
alpaca_secret_key = ALPACA_SECRET_KEY
 
api = tradeapi.REST(
   alpaca_api_key,
   alpaca_secret_key,
   api_version = "v2"
)
# Set timeframe to '1D'
timeframe = "1D"
# Set start and end datetimes between now and 3 years ago.
start_date = pd.Timestamp("2019-05-01", tz="America/New_York").isoformat()
end_date = pd.Timestamp("2021-06-27", tz="America/New_York").isoformat()
# Set the ticker information
tickers = ["SQ","ENPH","UBER","SPCE"]
# Get 3 year's worth of historical price data for Microsoft and Coca-Cola
df_ticker = api.get_barset(
   tickers,
   timeframe,
   start=start_date,
   end=end_date,
   limit=1000,
).df
# Display sample data
df_ticker.head()

ENPH                                     SPCE  \
                            open     high      low   close    volume open   
time                                                                        
2019-05-01 00:00:00-04:00  12.30  13.2000  12.0000  12.975  15294259  NaN   
2019-05-02 00:00:00-04:00  12.40  13.0400  12.3600  12.940   3509876  NaN   
2019-05-03 00:00:00-04:00  12.93  13.8792  12.9300  13.830   3954682  NaN   
2019-05-06 00:00:00-04:00  13.50  13.8950  13.4301  13.740   2394985  NaN   
2019-05-07 00:00:00-04:00  13.65  14.2900  13.6500  14.210   3189606  NaN   

                                                    SQ                        \
                          high low close volume   open   high     low  close   
time                                                                           
2019-05-01 00:00:00-04:00  NaN NaN   NaN    NaN  73.95  74.73  73.171  73.67   
2019-05-02 00:00:00-04:00  NaN NaN   NaN    NaN  69.80  70.50  66.050  67.73   
2019-05-03 00:00:00-04:00  NaN NaN   NaN    NaN  67.91  68.67  66.600  68.52   
2019-05-06 00:00:00-04:00  NaN NaN   NaN    NaN  65.46  70.29  65.410  70.21   
2019-05-07 00:00:00-04:00  NaN NaN   NaN    NaN  69.98  70.34  67.370  68.41   

                                    UBER                        
                             volume open high low close volume  
time                                                            
2019-05-01 00:00:00-04:00  12270720  NaN  NaN NaN   NaN    NaN  
2019-05-02 00:00:00-04:00  33369047  NaN  NaN NaN   NaN    NaN  
2019-05-03 00:00:00-04:00   8847087  NaN  NaN NaN   NaN    NaN  
2019-05-06 00:00:00-04:00  12633902  NaN  NaN NaN   NaN    NaN  
2019-05-07 00:00:00-04:00  10006668  NaN  NaN NaN   NaN    NaN

In [34]:
SQ_df = df_ticker["SQ"].close
SQ_df.head

<bound method NDFrame.head of time
2019-05-01 00:00:00-04:00     73.67
2019-05-02 00:00:00-04:00     67.73
2019-05-03 00:00:00-04:00     68.52
2019-05-06 00:00:00-04:00     70.21
2019-05-07 00:00:00-04:00     68.41
                              ...  
2021-06-21 00:00:00-04:00    233.91
2021-06-22 00:00:00-04:00    235.98
2021-06-23 00:00:00-04:00    238.69
2021-06-24 00:00:00-04:00    244.28
2021-06-25 00:00:00-04:00    240.24
Name: close, Length: 544, dtype: float64>

In [35]:
#SQ_X = SQ_df.to_numpy()
#print (SQ_X)

[ 73.67    67.73    68.52    70.21    68.41    67.28    66.38    65.99
  62.38    64.12    65.2     66.41    65.3     64.38    65.94    66.4472
  63.75    64.66    65.84    63.23    63.65    61.95    60.63    63.3997
  64.93    65.79    68.45    70.37    70.17    70.49    72.18    71.58
  72.24    71.8346  72.65    74.42    72.9     72.705   69.86    69.96
  71.3     72.505   73.22    73.97    74.2638  74.32    73.41    78.03
  78.38    79.445   82.33    82.1019  80.57    80.86    81.03    78.48
  78.57    78.85    80.42    80.04    81.81    80.23    80.48    80.4
  81.1435  69.599   64.8475  64.6     65.01    66.3     65.      62.29
  63.01    61.53    61.99    62.87    64.11    64.4     65.42    64.67
  61.83    62.82    61.74    62.14    62.85    61.81    61.15    61.09
  63.045   61.98    61.45    60.5     59.18    57.79    58.32    59.25
  59.54    59.73    59.03    57.83    56.75    57.53    58.51    60.8
  60.76    62.005   61.61    60.06    62.06    62.64    62.25    60.81
  62

In [ ]:
# before the for loop, declare variables for each ticker for each model     i.e.  square linear regression/ square RNN

# Create For Loop; 
# Iterate through each ticker
# get closing value from alpacas data frame from each ticker

# Convert to numpy
# Run SKlearn code
# Run RNN code

# save output of the models to these variables

In [31]:
X = df.to_numpy()
print (X)

[[7.29300000e+01 7.31699980e+01 6.92600020e+01 6.98700030e+01
  6.98700030e+01 1.20327000e+07]
 [7.09800030e+01 7.20000000e+01 6.99100040e+01 6.99499970e+01
  6.99499970e+01 7.91180000e+06]
 [7.05700000e+01 7.15400010e+01 7.00500030e+01 7.12799990e+01
  7.12799990e+01 5.16380000e+06]
 ...
 [2.34910004e+02 2.35660004e+02 2.28820007e+02 2.33889999e+02
  2.33889999e+02 6.62890000e+06]
 [2.32889999e+02 2.36278000e+02 2.29807007e+02 2.35970001e+02
  2.35970001e+02 6.74890000e+06]
 [2.36899994e+02 2.43000000e+02 2.36860001e+02 2.38699997e+02
  2.38699997e+02 8.16550000e+06]]


In [32]:
from sklearn.preprocessing import MinMaxScaler
price = df[["Close"]]
scaler = MinMaxScaler(feature_range=(-1,1))
Y = scaler.fit_transform(price["Close"].values.reshape(-1,1))
X = scaler.fit_transform(X)

In [33]:
print(X)
#print(Y)

[[-0.71120888 -0.73112431 -0.69385724 -0.73347868 -0.73347868 -0.53668933]
 [-0.72755078 -0.74076821 -0.68846885 -0.73280782 -0.73280782 -0.73652155]
 [-0.7309868  -0.74455983 -0.68730828 -0.72165382 -0.72165382 -0.86977858]
 ...
 [ 0.64626028  0.6082262   0.62886521  0.64206636  0.64206636 -0.79873241]
 [ 0.62933168  0.61332013  0.63704725  0.65951019  0.65951019 -0.79291332]
 [ 0.66293734  0.66872732  0.69551525  0.68240516  0.68240516 -0.72421903]]


In [ ]:
def split_data(X, Y, lookback, split_ratio):
    
    data = []

    for index in range(len(X) - lookback): 
        data.append(X[index: index + lookback])

    data = np.array(data);
    test_set_size = int(np.round(split_ratio * data.shape[0]))
    train_set_size = data.shape[0] - (test_set_size)
    
    x_train = data[:train_set_size,:]
    y_train = Y[:train_set_size,:]
    
    x_test = data[train_set_size:,:]
    y_test = Y[train_set_size:,:]
    
    return [x_train, y_train, x_test, y_test]

lookback = 40 # sequence length
split_ratio = 0.1
x_train, y_train, x_test, y_test = split_data(X, Y, lookback, split_ratio)

print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)


In [ ]:
import torch
import torch.nn as nn

x_train = torch.from_numpy(x_train).type(torch.Tensor)
x_test = torch.from_numpy(x_test).type(torch.Tensor)
y_train = torch.from_numpy(y_train).type(torch.Tensor)
y_test = torch.from_numpy(y_test).type(torch.Tensor)

input_dim = 6
hidden_dim = 32
num_layers = 2
output_dim = 1
num_epochs = 100

learning_rate = 0.01

class MyModel(nn.Module):
    def __init__(self, input_dim, hidden_dim, num_layers, output_dim):
        super(MyModel, self).__init__()
        self.hidden_dim = hidden_dim
        self.num_layers = num_layers
        
        self.lstm = nn.LSTM(input_dim, hidden_dim, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_dim, output_dim)
    def forward(self, x):
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_dim).requires_grad_()
        c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_dim).requires_grad_()
        out, (hn, cn) = self.lstm(x, (h0.detach(), c0.detach()))
        out = self.fc(out[:, -1, :]) 
        return out

In [ ]:
model = MyModel(input_dim = input_dim, hidden_dim = hidden_dim, num_layers = num_layers, output_dim = output_dim)
loss_func = torch.nn.MSELoss(reduction='mean')
optimizer=torch.optim.Adam(model.parameters(), lr=learning_rate)

In [ ]:
import time
n_epochs = 100
start_time=time.time()
for e in range(n_epochs):
  y_train_pred = model(x_train)
  loss = loss_func(y_train_pred, y_train)
  print(f"Epoch: {e}\tLoss: {loss.item()}")
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()
elapsed_time = time.time() - start_time
print(f"Total time for training: {elapsed_time}")

In [ ]:
# how do you use this on current data in order to get a predicted number?

# feed current data into this model?
 # create for loops
# are we validating model?

# make predictions and validate model